version: "3.8"

services:
  user_management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    environment:
      - ENV=development
      - CONFIG_FILE=config-local.yml
    depends_on:
      - mysql_user_management
    networks:
      - user_management_network
  mysql_user_management:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_management
      MYSQL_USER: owner
      MYSQL_PASSWORD: owner1234
    volumes:
      - mysql_user_management_data:/var/lib/mysql
    networks:
      - user_management_network

networks:
  user_management_network:
volumes:
  mysql_user_management_data:
